/*
 * MainForm.java
 *
 * Created on 6 de Agosto de 2007, 08:42
 */

package sqltocode;

/**
 *
 * @author  gustavoh
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtCode = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSql = new javax.swing.JTextArea();
        btnConvert = new javax.swing.JButton();
        btnSelectAll = new javax.swing.JButton();
        cmbType = new javax.swing.JComboBox();
        chkDeclare = new javax.swing.JCheckBox();
        txtVarName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convert Sql to Java (and Others)");

        txtCode.setColumns(20);
        txtCode.setRows(5);
        jScrollPane2.setViewportView(txtCode);

        txtSql.setColumns(20);
        txtSql.setRows(5);
        jScrollPane1.setViewportView(txtSql);

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        btnSelectAll.setText("Select All");
        btnSelectAll.setEnabled(false);
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "String", "string", "StringBuilder", "StringBuffer", "char[]" }));

        chkDeclare.setSelected(true);
        chkDeclare.setText("Declare variable");
        chkDeclare.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkDeclare.setMargin(new java.awt.Insets(0, 0, 0, 0));

        txtVarName.setText("sql");

        jLabel1.setText("Variable name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectAll)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(txtVarName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkDeclare, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvert)
                    .addComponent(btnSelectAll)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDeclare)
                    .addComponent(jLabel1)
                    .addComponent(txtVarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
    this.txtCode.selectAll();
}//GEN-LAST:event_btnSelectAllActionPerformed

private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed

    

    VariableType conv = new VariableType((String)cmbType.getSelectedItem());

    conv.setDeclare(chkDeclare.isSelected());
    conv.setVarName(txtVarName.getText());

    txtCode.setText(conv.ConvertText(txtSql.getText()));
  
    
      /*  
    String tmp = txtSql.getText().replaceAll("\n\r", "\n");
    String vet[] = tmp.split("\n");
    StringBuffer out = new StringBuffer();
    out.append(" sql = \"\";\n");
    for(String v : vet){
        out.append(" sql += \" " + v + " \\n\";\n");
    }
    */
   // txtCode.setText(out.toString());
}//GEN-LAST:event_btnConvertActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JCheckBox chkDeclare;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCode;
    private javax.swing.JTextArea txtSql;
    private javax.swing.JTextField txtVarName;
    // End of variables declaration//GEN-END:variables
    
}
